
# 服务配置
server:
  port: 8080
# servlet:
#    context-path: /gavin

# springboot
spring:
  profiles:
    active: dev
  application:
    name: springboot-web
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 初始化时运行sql脚本
    #schema: classpath:sql/schema.sql
    #initialization-mode: always
    druid:
      # 开启druid监控servlet
      stat-view-servlet:
        enabled: true
        login-username: admin
        loginPassword: 123456
      # 开启druid监控filter
      web-stat-filter:
        enabled: true

# mybatis-puls
mybatis-plus:
  mapper-locations: classpath:com/gavin/mapper/*Mapper.xml
  typeAliasesPackage: com.gavin.po
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration:
    mapUnderscoreToCamelCase: true

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  params: count=countSql
  supportMethodsArguments: true

# 日志
logging:
  file:
    name: ${spring.application.name}
    path: /var/${spring.application.name}/log
  charset: UTF-8
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    root: info
    com.gavin.springboot.mapper.TVehBaseMapper: debug
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 10MB
      max-history: 7
    file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz


